# Generated by Django 5.1.7 on 2025-05-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='disponibilidad',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reserva',
            table=None,
        ),
    ]
