# Generated by Django 5.1.7 on 2025-05-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_administrador', '0002_alter_administrador_table_alter_disponibilidad_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='ADMINISTRADOR',
        ),
        migrations.AlterModelTable(
            name='disponibilidad',
            table='DISPONIBILIDAD',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='RESERVA',
        ),
    ]
