# Generated by Django 5.1.7 on 2025-06-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_administrador', '0003_remove_disponibilidad_dia'),
    ]

    operations = [
        # Remove the 'DIA' column from the DISPONIBILIDAD table
        migrations.RunSQL(
            sql=[
                'ALTER TABLE DISPONIBILIDAD MODIFY DIA NULL;',
                'ALTER TABLE DISPONIBILIDAD DROP COLUMN DIA;',
            ],
            reverse_sql=[
                'ALTER TABLE DISPONIBILIDAD ADD DIA VARCHAR2(9) NOT NULL;',
            ]
        ),
    ]
