# Generated by Django 5.0.7 on 2024-08-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
