# Generated by Django 5.1 on 2025-03-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
    ]
