# Generated by Django 5.1.7 on 2025-03-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0002_alter_reserva_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
