# Generated by Django 5.1.7 on 2025-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'ADMINISTRADOR',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('servicio', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para reserva')),
                ('intervalo', models.PositiveSmallIntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=30, verbose_name='Duracion de cada turno')),
                ('es_franja_maestra', models.BooleanField(default=False, verbose_name='¿Es una franja horaria maestra?')),
                ('franja_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_franjas', to='servicios.disponibilidad', verbose_name='Franja original')),
            ],
            options={
                'db_table': 'DISPONIBILIDAD',
            },
        ),
        migrations.CreateModel(
            name='ServicioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=9)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='servicios.disponibilidad')),
            ],
            options={
                'verbose_name': 'Día del servicio',
                'verbose_name_plural': 'Días del servicio',
                'db_table': 'SERVICIO_DIA',
            },
        ),
    ]
