# Generated by Django 5.1.7 on 2025-06-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
    migrations.AlterField(
        model_name='disponibilidad',
        name='intervalo',
        field=models.PositiveSmallIntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=30, verbose_name='Duracion de cada turno'),
    ),
    migrations.AlterField(
        model_name='disponibilidad',
        name='es_franja_maestra',
        field=models.BooleanField(default=False, verbose_name='¿Es una franja horaria maestra?'),
    ),
    migrations.AlterField(
        model_name='disponibilidad',
        name='franja_padre',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_franjas', to='servicios.disponibilidad', verbose_name='Franja original'),
    ),
    ]
