# Generated by Django 5.1.7 on 2025-06-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=9)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='servicios.disponibilidad')),
            ],
            options={
                'verbose_name': 'Día del servicio',
                'verbose_name_plural': 'Días del servicio',
                'db_table': 'SERVICIO_DIA',
            },
        ),
    ]
