# Generated by Django 5.1.7 on 2025-07-18 01:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_add_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_servicio',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en la que se ofrece el servicio. No puede ser anterior a hoy.', validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 17))], verbose_name='Fecha del servicio'),
            preserve_default=False,
        ),
    ]
