# Generated by Django 5.1.7 on 2025-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_serviciodia'),
    ]

operations = [
    # 1. Primero elimina la restricción CHECK
    migrations.RunSQL(
        sql='ALTER TABLE DISPONIBILIDAD DROP CONSTRAINT SYS_C008450;',
        reverse_sql='ALTER TABLE DISPONIBILIDAD ADD CONSTRAINT SYS_C008450 CHECK ("DIA" IS NOT NULL);'  # Opcional, para revertir
    ),
    
    # 2. Luego elimina el campo
    migrations.RemoveField(
        model_name='disponibilidad',
        name='dia',
    ),
]