# Generated by Django 5.1.7 on 2025-07-22 23:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_disponibilidad_fecha_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='ubicacion',
            field=models.CharField(default='', max_length=200, verbose_name='Ubicación del servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_servicio',
            field=models.DateField(help_text='Fecha en la que se ofrece el servicio. No puede ser anterior a hoy.', validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 22))], verbose_name='Fecha del servicio'),
        ),
    ]
