# Generated by Django 5.1.7 on 2025-07-22 23:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_disponibilidad_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 22))], verbose_name='Fecha de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 22))], verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]