# Generated by Django 5.1.7 on 2025-07-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_disponibilidad_fecha_fin_disponibilidad_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='fecha_servicio',
        ),
    ]
