# Generated by Django 5.1.7 on 2025-07-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_disponibilidad_fecha_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioDia',
        ),
    ]
