# Generated by Django 5.1.7 on 2025-07-24 01:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_delete_serviciodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 23))], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 23))], verbose_name='Fecha de inicio'),
        ),
    ]
