# Generated by Django 5.1.7 on 2025-08-09 15:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duración estándar para este servicio', verbose_name='Duración estimada')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este servicio', verbose_name='¿Activo?')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio base')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 9))], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 9))], verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='servicios.servicio', verbose_name='Servicio asociado'),
        ),
    ]
