# Generated by Django 5.1.7 on 2025-08-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_servicio_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
    ]
