# Generated by Django 5.1.7 on 2025-08-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_remove_servicio_precio'),
    ]

   
    operations = [
        migrations.RunSQL(
            "ALTER TABLE DISPONIBILIDAD DROP COLUMN SERVICIO_TEMP;",
            reverse_sql="ALTER TABLE DISPONIBILIDAD ADD SERVICIO_TEMP NUMBER(19,0);"
        ),
        migrations.RunSQL(
            "ALTER TABLE DISPONIBILIDAD DROP COLUMN SERVICIO_TEMP_ID;",
            reverse_sql="ALTER TABLE DISPONIBILIDAD ADD SERVICIO_TEMP_ID NUMBER(19,0);"
        ),
    ]
