# Generated by Django 5.1.7 on 2025-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_remove_disponibilidad_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='servicio',
        ),
    ]
