# Generated by Django 5.1.7 on 2025-08-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_remove_disponibilidad_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='servicio',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='servicios.servicio', verbose_name='Servicio asociado'),
            preserve_default=False,
        ),
    ]
