# Generated by Django 5.1.7 on 2025-08-10 16:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_disponibilidad_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 10))], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 10))], verbose_name='Fecha de inicio'),
        ),
    ]
