# Generated by Django 5.1.7 on 2025-08-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'managed': False},
        ),
    ]
