# Generated by Django 5.1.7 on 2025-08-24 13:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_alter_administrador_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 24))], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 24))], verbose_name='Fecha de inicio'),
        ),
    ]
