# Generated by Django 5.1.7 on 2025-09-20 21:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 9, 20))], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 9, 20))], verbose_name='Fecha de inicio'),
        ),
    ]
