# Generated by Django 5.1.7 on 2025-06-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios_administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_administrador.administrador')),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_administrador.disponibilidad')),
            ],
            options={
                'db_table': 'RESERVA_USUARIOS',
            },
        ),
    ]
