# Generated by Django 5.1.7 on 2025-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='temporal_field',
        ),
    ]
