# Generated by Django 5.1.7 on 2025-07-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0008_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('horario', models.CharField(max_length=50)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_rut', models.CharField(max_length=20)),
                ('cliente_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='servicios.disponibilidad')),
                ('servicio_nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.disponibilidad')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
