# Generated by Django 5.1.7 on 2025-07-03 01:17

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('reservas', '0001_initial'),  # Depende de tu migración inicial
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',  # ¡Usa el nombre exacto del modelo!
            name='cliente_telefono',
            field=models.CharField(max_length=15, blank=True, null=True),
        ),
    ]