# Generated by Django 5.1.7 on 2025-08-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicio_nombre',
        ),
    ]
