# Generated by Django 5.1.7 on 2025-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_add_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['dia_semana', 'hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], default=1, max_length=10, verbose_name='Dia de la semana'),
            preserve_default=False,
        ),
    ]
