# Generated by Django 5.1.7 on 2025-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
