# Generated by Django 5.1.7 on 2025-09-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_motivo_cancelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCancelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cancelacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelacion', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reserva Cancelada',
                'verbose_name_plural': 'Reservas Canceladas',
                'ordering': ['-fecha_cancelacion'],
            },
        ),
    ]
